/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmiTokenize;

import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;

import javax.swing.JOptionPane;

/**
 *
 * @author nikolay
 */
public class Client extends javax.swing.JFrame {

    private ServerInterface rmiServer;
    private int privilage;
    //private final JFrame user = new User();

    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
        initRMI();
        privilage = 0;
        tokenizePanel.setVisible(false);
        savePanel.setVisible(false);
        addAccountPanel.setVisible(false);
        btnLogout.setVisible(false);
    }

    public void initRMI() {
        try {
            Registry registry = LocateRegistry.getRegistry("localhost", 33333);
            rmiServer = (ServerInterface) registry.lookup("rmiServer");
            System.out.println("Server object " + rmiServer + " found");
        } catch (RemoteException | NotBoundException ex) {
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogin = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        tokenizePanel = new javax.swing.JPanel();
        txtNumber1 = new javax.swing.JTextField();
        detokenize = new javax.swing.JButton();
        txtNumber2 = new javax.swing.JTextField();
        txtToken2 = new javax.swing.JTextField();
        txtToken1 = new javax.swing.JTextField();
        btnTokenize = new javax.swing.JButton();
        addAccountPanel = new javax.swing.JPanel();
        txtUsernameReg = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPasswordReg = new javax.swing.JPasswordField();
        txtRepPasswordReg = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        savePanel = new javax.swing.JPanel();
        btnSaveSortedByToken = new javax.swing.JButton();
        txtFileSortedByToken = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSaveSortedByNumber = new javax.swing.JButton();
        txtFileSortedbyNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogin.setText("Not Logged in");

        LoginPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel2.setText("Password:");

        jLabel1.setText("Username:");

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin))
                .addContainerGap())
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addContainerGap())
        );

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        tokenizePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        detokenize.setText("Detokenize");
        detokenize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detokenizeActionPerformed(evt);
            }
        });

        txtNumber2.setEditable(false);

        txtToken1.setEditable(false);

        btnTokenize.setText("Tokenize");
        btnTokenize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTokenizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tokenizePanelLayout = new javax.swing.GroupLayout(tokenizePanel);
        tokenizePanel.setLayout(tokenizePanelLayout);
        tokenizePanelLayout.setHorizontalGroup(
            tokenizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tokenizePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tokenizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(detokenize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTokenize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(tokenizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtToken1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(txtNumber2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtToken2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumber1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tokenizePanelLayout.setVerticalGroup(
            tokenizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tokenizePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tokenizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTokenize))
                .addGap(9, 9, 9)
                .addComponent(txtToken1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tokenizePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtToken2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detokenize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        addAccountPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jLabel5.setText("Password:");

        jLabel4.setText("Repeat Password:");

        jLabel3.setText("Username:");

        jLabel8.setText("Create account:");

        javax.swing.GroupLayout addAccountPanelLayout = new javax.swing.GroupLayout(addAccountPanel);
        addAccountPanel.setLayout(addAccountPanelLayout);
        addAccountPanelLayout.setHorizontalGroup(
            addAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(addAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRepPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(addAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(btnRegister, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtUsernameReg, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addAccountPanelLayout.setVerticalGroup(
            addAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addAccountPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsernameReg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRepPasswordReg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegister)
                .addContainerGap())
        );

        savePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSaveSortedByToken.setText("Save");
        btnSaveSortedByToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSortedByTokenActionPerformed(evt);
            }
        });

        jLabel7.setText("Save Tokens to File sorted by card number");

        jLabel6.setText("Save Tokens to File sorted by token");

        btnSaveSortedByNumber.setText("Save");
        btnSaveSortedByNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSortedByNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout savePanelLayout = new javax.swing.GroupLayout(savePanel);
        savePanel.setLayout(savePanelLayout);
        savePanelLayout.setHorizontalGroup(
            savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(savePanelLayout.createSequentialGroup()
                        .addGroup(savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSaveSortedByToken, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaveSortedByNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFileSortedByToken, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFileSortedbyNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        savePanelLayout.setVerticalGroup(
            savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveSortedByToken)
                    .addComponent(txtFileSortedByToken, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addGroup(savePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveSortedByNumber)
                    .addComponent(txtFileSortedbyNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLogout))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tokenizePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(4, 4, 4))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(savePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogout))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tokenizePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addAccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        //try to login via rmi 
        String username = txtUsername.getText();
        String password = new String(txtPassword.getPassword());
        try {
            privilage = rmiServer.login(username, password);
        } catch (RemoteException ex) {
            System.out.println("RemoteException");
        }
        //the privilage determines which panels will show 
        if (privilage > 0) {
            lblLogin.setText("Logged in as " + username);
            LoginPanel.setVisible(false);
            btnLogout.setVisible(true);
            if (privilage >= 1) {
                tokenizePanel.setVisible(true);
            }
            if (privilage >= 2) {
                addAccountPanel.setVisible(true);
                savePanel.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Incorrect username/password");
        }
        System.out.println(privilage);
        txtUsername.setText("");
        txtPassword.setText("");


    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // Hide every panel except for the login
        JOptionPane.showMessageDialog(rootPane, "Logout successful");
        lblLogin.setText("Not Logged in");
        LoginPanel.setVisible(true);
        tokenizePanel.setVisible(false);
        savePanel.setVisible(false);
        addAccountPanel.setVisible(false);
        btnLogout.setVisible(false);
        clearTextFields();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnTokenizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTokenizeActionPerformed
        //try to tokenize the given card number
        String number = txtNumber1.getText();
        if(!number.matches("[\\d\\s]*")){
            JOptionPane.showMessageDialog(rootPane, "number must contain only digits and whitespaces");
            return;
        }
        String token = "";
        try {
            token = rmiServer.tokenize(number);
        } catch (InvallidTokenException ex) {
            JOptionPane.showMessageDialog(rootPane, "Invalid card number");
        } catch (RemoteException ex) {
            System.out.println("remoteException");
        }
        txtToken1.setText(token);
    }//GEN-LAST:event_btnTokenizeActionPerformed

    private void btnSaveSortedByTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSortedByTokenActionPerformed
        //save all tokens to a file, sorted by token
        String filename = txtFileSortedByToken.getText();
        if (filename.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "You must enter name of file");
        } else {
            try {
                rmiServer.TokensToFile(filename);
            } catch (RemoteException ex) {
                System.out.println("RemoteException: " + ex);
            }
        }

    }//GEN-LAST:event_btnSaveSortedByTokenActionPerformed

    private void btnSaveSortedByNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSortedByNumberActionPerformed
        //save all tokens to a file, sorted by card number
        String filename = txtFileSortedbyNumber.getText();
        if (filename.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "You must enter name of file");
        } else {
            try {
                rmiServer.NumberstoFile(filename);
            } catch (RemoteException ex) {
                System.out.println("RemoteException: " + ex);
            }
        }
    }//GEN-LAST:event_btnSaveSortedByNumberActionPerformed

    private void detokenizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detokenizeActionPerformed
        //try to find the card number corresponding to the given token
        String token = txtToken2.getText();
        if(!token.matches("[\\d\\s]*")){
            JOptionPane.showMessageDialog(rootPane, "token must contain only digits and whitespaces");
            return;
        }
        String number = "";
        try {
            number = rmiServer.detokenize(token);
            txtNumber2.setText(number);
        } catch (InvallidTokenException ex) {
            JOptionPane.showMessageDialog(rootPane, "Token doesn't map to any card number");
        } catch (RemoteException ex) {
            System.out.println("remoteException");
        }

    }//GEN-LAST:event_detokenizeActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        //try to register a new account
        String username = txtUsernameReg.getText();
        String pass = new String(txtPasswordReg.getPassword());
        String repPass = new String(txtRepPasswordReg.getPassword());
        if (username.equals("") || pass.equals("") || repPass.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "You must fill in all fields");
        } else if (!pass.equals(repPass)) {
            JOptionPane.showMessageDialog(rootPane, "Passwords doesn't match");
        } else {
            try {
                Boolean added = rmiServer.addAccount(username, pass, 1);
                if (added) {
                    JOptionPane.showMessageDialog(rootPane, "Registration Successful");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Duplicate username");
                }
                txtUsernameReg.setText("");
                txtPasswordReg.setText("");
                txtRepPasswordReg.setText("");
            } catch (RemoteException ex) {
                System.out.println("RemoteException");
            }
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void clearTextFields(){
    txtFileSortedByToken.setText("");
    txtFileSortedbyNumber.setText("");
    txtNumber1.setText("");
    txtNumber2.setText("");
    txtPassword.setText("");
    txtPasswordReg.setText("");
    txtRepPasswordReg.setText("");
    txtToken1.setText("");
    txtToken2.setText("");
    txtUsername.setText("");
    txtUsernameReg.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPanel addAccountPanel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSaveSortedByNumber;
    private javax.swing.JButton btnSaveSortedByToken;
    private javax.swing.JButton btnTokenize;
    private javax.swing.JButton detokenize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JPanel savePanel;
    private javax.swing.JPanel tokenizePanel;
    private javax.swing.JTextField txtFileSortedByToken;
    private javax.swing.JTextField txtFileSortedbyNumber;
    private javax.swing.JTextField txtNumber1;
    private javax.swing.JTextField txtNumber2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordReg;
    private javax.swing.JPasswordField txtRepPasswordReg;
    private javax.swing.JTextField txtToken1;
    private javax.swing.JTextField txtToken2;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsernameReg;
    // End of variables declaration//GEN-END:variables
}
